# Generated by Django 5.2.17 on 2026-09-24 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_invite_starting_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('issue', 'Issue reported'), ('message', 'Message'), ('pr', 'PR'), ('program_ending', 'Program running out'), ('metrics_missing', 'Missing metrics'), ('missed', 'Missed session'), ('video', 'Form video'), ('week_published', 'Week published')], max_length=20)),
                ('dedupe_key', models.CharField(max_length=80)),
                ('text', models.CharField(max_length=300)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.athlete')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'kind', 'dedupe_key'), name='one_notification_per_key')],
            },
        ),
    ]
