# Generated by Django 5.2.17 on 2026-09-23 19:12

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64, validators=[apps.accounts.models.validate_timezone]),
        ),
    ]
