# Generated by Django 5.2.17 on 2026-09-23 19:28

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_timezone_validator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('units', models.CharField(choices=[('kg', 'kilograms'), ('lb', 'pounds')], default='kg', max_length=2)),
                ('timezone', models.CharField(default='UTC', max_length=64, validators=[apps.accounts.models.validate_timezone])),
                ('week_type_colours', models.JSONField(blank=True, default=dict, validators=[apps.accounts.models.validate_week_type_colours])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_class', models.CharField(blank=True, max_length=20)),
                ('competition_name', models.CharField(blank=True, max_length=120)),
                ('competition_date', models.DateField(blank=True, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('years_training', models.CharField(blank=True, choices=[('<1', '< 1'), ('1-3', '1–3'), ('3-5', '3–5'), ('5+', '5+')], max_length=4)),
                ('units', models.CharField(choices=[('kg', 'kilograms'), ('lb', 'pounds')], default='kg', max_length=2)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__name'],
            },
        ),
        migrations.CreateModel(
            name='BodyweightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(choices=[('onboarding', 'Onboarding'), ('athlete', 'Athlete'), ('coach', 'Coach'), ('session', 'Session')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodyweights', to='accounts.athlete')),
            ],
            options={
                'verbose_name_plural': 'bodyweight entries',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Head coach', max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coaches', to='accounts.gym')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='accounts.coach'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='accounts.gym'),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('token', models.CharField(default=apps.accounts.models.new_invite_token, editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.accounts.models.default_invite_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='accounts.coach')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaxEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reps', models.PositiveSmallIntegerField(default=1)),
                ('source', models.CharField(choices=[('onboarding', 'Onboarding'), ('athlete', 'Athlete'), ('coach', 'Coach'), ('session', 'Session')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxes', to='accounts.athlete')),
            ],
            options={
                'verbose_name_plural': 'max entries',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
