# Generated by Django 5.2.17 on 2026-09-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_gym_athlete_bodyweightentry_coach_athlete_coach_and_more'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxentry',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='max_entries', to='exercises.exercise'),
        ),
        migrations.AddConstraint(
            model_name='bodyweightentry',
            constraint=models.CheckConstraint(condition=models.Q(('kg__gt', 0)), name='bodyweight_positive'),
        ),
        migrations.AddConstraint(
            model_name='maxentry',
            constraint=models.CheckConstraint(condition=models.Q(('kg__gt', 0)), name='max_positive'),
        ),
    ]
