# Generated by Django 5.2.17 on 2026-09-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_gym_week_type_colours'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='week_start',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (6, 'Sunday')], default=0, help_text='The day training weeks start on (Python weekday: 0 = Monday, 6 = Sunday).'),
        ),
    ]
