# Generated by Django 5.2.17 on 2026-09-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_gym_week_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='max_updates',
            field=models.CharField(choices=[('approve', 'Coach approves'), ('auto', 'Automatically')], default='approve', help_text='When a session beats a working max: update it straight away, or wait for the coach.', max_length=8),
        ),
    ]
