# Generated by Django 5.2.17 on 2026-09-23 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_athlete_max_updates'),
        ('workouts', '0002_sessionlog_sessionexercise_issuereport_checkinanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxentry',
            name='set_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='max_entries', to='workouts.setlog'),
        ),
    ]
