# Generated by Django 5.2.17 on 2026-09-23 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_maxentry_set_log'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='starting_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='library.template'),
        ),
    ]
