# Generated by Django 5.2.17 on 2026-09-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_invite_starting_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='digest',
            field=models.BooleanField(default=True, help_text='Email a morning digest of new attention items.'),
        ),
        migrations.AddField(
            model_name='coach',
            name='last_digest_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
