# Generated by Django 5.2.17 on 2026-09-23 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_maxentry_exercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('scale', '1–10 scale'), ('choice', 'Multiple choice')], max_length=10)),
                ('text', models.CharField(max_length=200)),
                ('low_label', models.CharField(blank=True, max_length=60)),
                ('high_label', models.CharField(blank=True, max_length=60)),
                ('options', models.JSONField(blank=True, default=list)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.athlete')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_questions', to='accounts.gym')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('athlete__isnull', True), ('gym__isnull', False)), models.Q(('athlete__isnull', False), ('gym__isnull', True)), _connector='OR'), name='checkin_question_has_exactly_one_owner')],
            },
        ),
    ]
