# Generated by Django 5.2.17 on 2026-09-23 22:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_athlete_max_updates'),
        ('exercises', '0006_switch_to_category_and_tag_models'),
        ('programs', '0003_programday_program_programsession_prescription_and_more'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('checkin_skipped', models.BooleanField(default=False)),
                ('session_rpe', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(blank=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='accounts.athlete')),
                ('program_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='programs.programsession')),
                ('week_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_logs', to='programs.weektype')),
            ],
            options={
                'ordering': ['-date', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('prescribed', models.JSONField(blank=True, default=dict)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_exercises', to='exercises.exercise')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged', to='programs.prescription')),
                ('session_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.sessionlog')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pain', 'Pain / possible injury'), ('equipment', 'Equipment not available'), ('prescription', 'Prescription looks wrong'), ('other', 'Something else')], max_length=14)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='accounts.athlete')),
                ('session_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='workouts.sessionlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckinAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question_text', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('scale', '1–10 scale'), ('choice', 'Multiple choice')], max_length=10)),
                ('value', models.CharField(max_length=200)),
                ('other_text', models.TextField(blank=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='workouts.checkinquestion')),
                ('session_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='workouts.sessionlog')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('load_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('rir', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('logged_at', models.DateTimeField(auto_now=True)),
                ('max_dismissed', models.BooleanField(default=False)),
                ('session_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.sessionexercise')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionlog',
            constraint=models.UniqueConstraint(condition=models.Q(('program_session__isnull', False)), fields=('program_session',), name='one_log_per_program_session'),
        ),
        migrations.AddConstraint(
            model_name='checkinanswer',
            constraint=models.UniqueConstraint(fields=('session_log', 'question'), name='one_answer_per_question'),
        ),
        migrations.AddConstraint(
            model_name='setlog',
            constraint=models.UniqueConstraint(fields=('session_exercise', 'set_number'), name='unique_set_per_exercise'),
        ),
    ]
