# Generated by Django 5.2.17 on 2026-09-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_formvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinquestion',
            name='detail_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='warmup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkinanswer',
            name='type',
            field=models.CharField(choices=[('scale', '1–10 scale'), ('choice', 'Multiple choice'), ('text', 'Short answer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='checkinanswer',
            name='value',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='checkinquestion',
            name='type',
            field=models.CharField(choices=[('scale', '1–10 scale'), ('choice', 'Multiple choice'), ('text', 'Short answer')], max_length=10),
        ),
    ]
