# Generated by Django 5.2.17 on 2026-09-23 19:28

import apps.exercises.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_gym_athlete_bodyweightentry_coach_athlete_coach_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, help_text="Stable id for starter-library exercises (e.g. 'sn'), so code can find the snatch even if a coach renames it. Blank for exercises a coach creates.", max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('snatch', 'Snatch'), ('clean_jerk', 'Clean & Jerk'), ('squat', 'Squat'), ('pull', 'Pull'), ('press', 'Press'), ('accessory', 'Accessory'), ('conditioning', 'Conditioning'), ('mobility', 'Mobility')], max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None, validators=[apps.exercises.models.validate_tags])),
                ('measure', models.CharField(choices=[('reps', 'Reps'), ('time', 'Time'), ('distance', 'Distance')], default='reps', max_length=10)),
                ('reps_per_rep', models.PositiveSmallIntegerField(default=1, help_text='2 for a "1+1" complex')),
                ('youtube_url', models.URLField(blank=True)),
                ('cue', models.TextField(blank=True)),
                ('archived', models.BooleanField(default=False)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='accounts.gym')),
                ('percent_of', models.ForeignKey(blank=True, help_text="The max percentages are worked from. Empty means this exercise's own max.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercises.exercise')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('gym', 'name'), name='unique_exercise_name_per_gym'), models.UniqueConstraint(condition=models.Q(('key', ''), _negated=True), fields=('gym', 'key'), name='unique_exercise_key_per_gym')],
            },
        ),
    ]
