# Generated by Django 5.2.17 on 2026-09-23 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_maxentry_exercise_and_more'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='key',
            field=models.CharField(blank=True, help_text="Marks exercises that came from the starter library (e.g. 'sn'), so the library can be refreshed without duplicates. Blank for exercises a coach creates. Nothing else may depend on it: features use the gym's own settings, e.g. TrackedLift.", max_length=20),
        ),
        migrations.CreateModel(
            name='TrackedLift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_by', to='exercises.exercise')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_lifts', to='accounts.gym')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('gym', 'exercise'), name='unique_tracked_lift_per_gym')],
            },
        ),
    ]
