# Generated by Django 5.2.17 on 2026-09-23 20:31

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_maxentry_exercise_and_more'),
        ('exercises', '0003_track_default_lifts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.gym')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='exercises.category'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.gym')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='tag_set',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='exercises.tag'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('gym'), name='unique_category_name_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('gym'), name='unique_tag_name_per_gym'),
        ),
    ]
