# Generated by Django 5.2.17 on 2026-09-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_switch_to_category_and_tag_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='warmup',
            field=models.BooleanField(default=False, help_text='A warm-up drill: added to sessions as part of the warm-up checklist.'),
        ),
    ]
