# Generated by Django 5.2.17 on 2026-09-23 20:31

import apps.programs.models
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_maxentry_exercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('colour', models.CharField(max_length=7, validators=[apps.programs.models.validate_colour])),
                ('order', models.PositiveIntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_types', to='accounts.gym')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('gym'), name='unique_week_type_name_per_gym')],
            },
        ),
    ]
