# Generated by Django 5.2.17 on 2026-09-23 21:09

import django.db.models.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_gym_week_start'),
        ('exercises', '0006_switch_to_category_and_tag_models'),
        ('programs', '0002_copy_week_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('start_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='accounts.athlete')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='programs.programday')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveSmallIntegerField(default=3)),
                ('rep_scheme', models.CharField(blank=True, max_length=30)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('load_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('load_basis', models.CharField(choices=[('percent', '% of max'), ('rpe', 'RPE'), ('weight', 'Weight'), ('bodyweight', 'Bodyweight'), ('none', 'No load')], default='none', max_length=12)),
                ('rir', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('custom_fields', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='exercises.exercise')),
                ('tag_slot_tags', models.ManyToManyField(blank=True, related_name='+', to='exercises.tag')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='programs.programsession')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('focus_note', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='programs.program')),
                ('week_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_weeks', to='programs.weektype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='programday',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='programs.programweek'),
        ),
        migrations.CreateModel(
            name='PrescribedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('rep_scheme', models.CharField(blank=True, max_length=30)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('load_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_overrides', to='programs.prescription')),
            ],
            options={
                'ordering': ['set_number'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('prescription', 'set_number'), name='unique_set_per_prescription')],
            },
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('athlete',), name='one_active_program_per_athlete'),
        ),
        migrations.AddConstraint(
            model_name='programweek',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('program', 'order'), name='unique_week_order_per_program'),
        ),
        migrations.AddConstraint(
            model_name='programday',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('week', 'date'), name='unique_day_per_week'),
        ),
    ]
