# Generated by Django 5.2.17 on 2026-09-23 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('programs', '0003_programday_program_programsession_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='library.template'),
        ),
    ]
