# Generated by Django 5.2.17 on 2026-09-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_edithistory_habit_habitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='rir_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='section',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='prescription',
            name='section_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prescription',
            name='superset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='warmup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='note',
            field=models.TextField(blank=True, help_text='Goal, rest, nutrition: shown to the athlete.'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='rep_scheme',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
