"""Installing the athlete app to a phone's home screen (a PWA): the web manifest, a small
service worker, and the page shown when a screen is opened offline.

The service worker caches the static files (CSS, JS, icons) so the app opens fast, and
shows the offline page instead of the browser's error when there's no signal. It does
not queue set logging offline (docs/BUILD_PLAN.md, "Still open"). It's served from the
site root so its scope covers /app/.
"""

import hashlib
import json
from pathlib import Path

from django.contrib.staticfiles import finders
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.templatetags.static import static
from django.urls import reverse
from django.views.decorators.cache import cache_control

PRECACHE = [
    "css/tokens.css",
    "css/icons.css",
    "css/app.css",
    "css/shell.css",
    "js/app.js",
    "vendor/htmx-2.0.11.min.js",
    "vendor/alpine-3.17.4.min.js",
    "icons/icon-192.png",
]


@cache_control(max_age=3600)
def manifest(request):
    return JsonResponse(
        {
            "name": "Platform",
            "short_name": "Platform",
            "description": "Your training, check-ins and coach, in one app.",
            "start_url": "/app/",
            "scope": "/",
            "display": "standalone",
            "background_color": "#FFFFFF",
            "theme_color": "#1F4FD8",
            "icons": [
                {"src": static("icons/icon-192.png"), "sizes": "192x192", "type": "image/png"},
                {"src": static("icons/icon-512.png"), "sizes": "512x512", "type": "image/png"},
                {
                    "src": static("icons/maskable-192.png"),
                    "sizes": "192x192",
                    "type": "image/png",
                    "purpose": "maskable",
                },
                {
                    "src": static("icons/maskable-512.png"),
                    "sizes": "512x512",
                    "type": "image/png",
                    "purpose": "maskable",
                },
            ],
        },
        content_type="application/manifest+json",
    )


def _version(urls):
    """Changes whenever a cached file changes. In production the URLs carry content hashes
    already; locally they don't, so the files' contents go in too, or the browser would keep
    serving old CSS and JavaScript from the worker's cache after an edit."""
    digest = hashlib.sha1("".join(urls).encode())
    for path in PRECACHE:
        found = finders.find(path)
        if found:
            digest.update(Path(found).read_bytes())
    return digest.hexdigest()[:12]


@cache_control(no_cache=True)
def service_worker(request):
    urls = [static(p) for p in PRECACHE] + [reverse("offline")]
    version = _version(urls)
    js = (
        SERVICE_WORKER.replace("__VERSION__", version)
        .replace("__URLS__", json.dumps(urls))
        .replace("__OFFLINE__", reverse("offline"))
    )
    return HttpResponse(js, content_type="application/javascript")


def offline(request):
    return render(request, "offline.html")


SERVICE_WORKER = """// Generated by apps/dashboard/pwa.py
const CACHE = "platform-__VERSION__";
const PRECACHE = __URLS__;

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;  // the video bucket, fonts, YouTube
  if (url.pathname.startsWith("/static/")) {
    event.respondWith(
      caches.match(request).then((hit) => hit || fetch(request).then((response) => {
        if (response.ok) {  // never keep an error page in place of a file
          const copy = response.clone();
          caches.open(CACHE).then((c) => c.put(request, copy));
        }
        return response;
      }))
    );
    return;
  }
  if (request.mode === "navigate") {
    event.respondWith(fetch(request).catch(() => caches.match("__OFFLINE__")));
  }
});
"""
